name: "build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./notebooks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run the notebooks
        run: |
          pip install -r requirements.txt
          for f in *.ipynb; 
            do echo "Processing $f file...";
            # jupyter nbconvert --execute --to notebook --inplace $f
            jupyter nbconvert $f --to slides
          done
          mkdir _site
          mv *.html _site
          mv *.ipynb _site
          cp datasets/* _site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: notebooks/_site
      - name: Build local Jupyter
        run: docker compose build